config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  get 'terms', to: 'tops#terms'
  get 'privacy', to: 'tops#privacy'

  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/guest_login', to: 'sessions#guest_login'

  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauths/oauth', to: 'oauths#oauth', as: :auth_at_provider

  resources :password_resets, only: %i[new create edit update]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :menus, only: %i[index edit update]

  resources :videos do
    get 'search_videos', on: :collection
  end

  resources :dishes, only: %i[index edit update]

  resource :profile, only: %i[show edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates :name, presence: true

  has_many :menus, dependent: :destroy
  has_one :video, dependent: :destroy
  has_many :dish_genre_tags, dependent: :destroy
  has_many :genre_tags, through: :dish_genre_tags
  has_many :dish_ingredient_tags, dependent: :destroy
  has_many :ingredient_tags, through: :dish_ingredient_tags

end

app/models/dish_genre_tag.rb
class DishGenreTag < ApplicationRecord
  belongs_to :dish
  belongs_to :genre_tag
end

app/models/dish_ingredient_tag.rb
class DishIngredientTag < ApplicationRecord
  belongs_to :dish
  belongs_to :ingredient_tag
end

app/models/genre_tag.rb
class GenreTag < ApplicationRecord
  has_many :dish_genre_tags, dependent: :destroy
  has_many :dishes, through: :dish_genre_tags

  validates :name, presence: true
end

app/models/ingredient_tag.rb
class IngredientTag < ApplicationRecord
  has_many :dish_ingredient_tags, dependent: :destroy
  has_many :dishes, through: :dish_ingredient_tags

  validates :name, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user
  belongs_to :dish

  def start_time
    self.date
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :menus, dependent: :destroy
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :name, presence: true, length: {maximum: 20}
  validates :email, presence: true, length: {maximum: 100}, uniqueness: true
  validates :password, length: { minimum: 7 }, confirmation: true, if: -> { new_record? || changes[:crypted_password] }

  validates :reset_password_token, uniqueness: true, allow_nil: true

  enum role: { general: 0, admin: 1 }
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :dish

  validates :video_id, presence: true, uniqueness: true
  validates :title, presence: true, uniqueness: true
  validates :thumbnail, presence: true, uniqueness: true

  def self.search_by_dish(dish)
    response = YoutubeService.list_searches(
      'snippet',
      q: dish.name + "レシピ",
      type: 'video',
      max_results: 1,
      # 関連度が高い順
      order: "relevance",
    ).items

    if response.present?
      video = Video.new(
        video_id: response.first.id.video_id,
        title: response.first.snippet.title,
        thumbnail: response.first.snippet.thumbnails.high.url,
        dish: dish
      )
      video.save
    end
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :require_login

  def index
    return unless params[:date].present?

    start_date = params[:date].to_date.beginning_of_week
    end_date = start_date.end_of_week
    @week_menus = current_user.menus.where(date: start_date..end_date).order(date: :asc)

    if @week_menus.empty?
      create_weekly_menu(start_date)
      flash[:notice] = "#{start_date} から #{end_date} までの献立を作成しました！"
      redirect_to action: :index, date: params[:date]
    end
  end

  def create_weekly_menu(start_date)
    (start_date..start_date.end_of_week).each do |date|
      create_menu_for_date(date)
    end
  end

  def create_menu_for_date(date)
    return if current_user.menus.exists?(date: date)
    previous_menu = current_user.menus.find_by(date: date - 1.day)
    previous_genre_id = previous_menu&.dish&.genre_tags&.pluck(:id)
    dish = Dish.joins(:genre_tags).where.not(genre_tags: { id: previous_genre_id }).order("RANDOM()").first
    current_user.menus.create(date: date, dish: dish)
  end

  def edit
    @menu = current_user.menus.find(params[:id])
    @dishes = Dish.all
  end

  def update
    @menu = current_user.menus.find(params[:id])
    @menu.update(dish_id: params[:menu][:dish_id])
    redirect_to menus_path(date: @menu.date)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def show
    @current_user_menus = current_user.menus.includes(dish: [:ingredient_tags, :genre_tags])
  end

  def edit;end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :name)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :require_login

  def index;  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '', admin = false)
    base_title = if admin
                  'MenuVid(管理画面)'
                 else
                  'MenuVid'
                 end
    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end

  def default_meta_tags
    {
      site: 'MenuVid',
      title: 'MenuVid',
      reverse: true,
      charset: 'utf-8',
      description: 'MenuVid(メニュービッド)は、Youtube動画であなただけの献立を自動で作成してくれるサービスです。',
      keywords: 'Youtube,献立,料理',
      canonical: request.original_url,
      separator: '|',
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.png'), # 配置するパスやファイル名によって変更すること
        local: 'ja-JP'
      },
      # Twitter用の設定を個別で設定する
      twitter: {
        card: 'summary_large_image', # Twitterで表示する場合は大きいカードにする
        site: '@', # アプリの公式Twitterアカウントがあれば、アカウント名を書く
        image: image_url('ogp.png') # 配置するパスやファイル名によって変更すること
      }
    }
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/profiles/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="bg-gray-100 py-6">
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
    <h1 class="text-3xl font-bold text-gray-900 mb-8"><%= t('.title') %></h1>
    <%= form_with model: @user, url: profile_path, local: true do |f| %>
      <div class="bg-white rounded-lg shadow-sm p-6 mb-8">
        <div class="mb-4">
          <%= f.label :email, class: "block text-gray-700 font-semibold mb-2" %>
          <%= f.email_field :email, class: "form-input w-full py-2 px-4 rounded-lg border-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-blue-400", placeholder: "Your email address" %>
        </div>
        <div class="mb-4">
          <%= f.label :name, class: "block text-gray-700 font-semibold mb-2" %>
          <%= f.text_field :name, class: "form-input w-full py-2 px-4 rounded-lg border-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-blue-400", placeholder: "Your name" %>
        </div>
        <div class="text-center">
          <%= f.submit "更新", class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/profiles/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="py-10">
  <div class="container mx-auto px-4">
    <h1 class="text-4xl font-bold text-center mb-10"><%= t('.title') %></h1>
    <%# プロフィール欄 %>
    <div class="bg-base-200 mb-10">
      <div class="text-center pt-10">
        <div class="flex flex-col">
          <h2 class="text-xl font-semibold mb-3">メールアドレス</h2>
          <p class="text-gray-600 text-lg mb-10"><%= current_user.email %></p>
          <h2 class="text-xl font-semibold mb-3">名前</h2>
          <p class="text-gray-600 text-lg mb-10"><%= current_user.name %></p>
          <%= link_to t('defaults.edit'), edit_profile_path, class: 'btn mb-10 mx-auto' %>
        </div>
      </div>
    </div>
  </div>
  <%# カレンダー %>
  <div class="bg-white rounded-lg shadow-lg mt-20 text-center ml-2">
    <h1 class="font-bold underline underline-offset-8 mb-5"><%= @current_user.name %>さんの献立カレンダー</h1>
      <%= month_calendar partial: 'simple_calendar/calendar', events: @current_user_menus, class: 'overflow-auto' do |date, menus| %>
        <div class="flex items-center justify-between border-b border-gray-200 py-3">
          <div class="flex items-center">
            <div class="w-8 h-8 flex items-center justify-center rounded-full bg-gray-100 text-gray-800 mr-2"><%= date.to_s.slice(8, 2) %></div>
              <div>
                <% if menus.present? %>
                  <% menus.each do |menu| %>
                    <p><%= link_to menu.dish.name, menus_path(date: date) %></p>
                    <% if menu.dish.genre_tags.first && menu.dish.genre_tags.first.name.present? %>
                      <span class="text-xs bg-error  px-2 py-1 rounded-full mr-2"><%= menu.dish.genre_tags.first.name %></span>
                    <% end %>
                    <% if menu.dish.ingredient_tags.first && menu.dish.ingredient_tags.first.name.present? %>
                      <span class="bg-warning text-xs px-2 py-1 rounded-full"><%= menu.dish.ingredient_tags.first.name %></span>
                    <% end %>
                  <% end %>
                <% else %>
                  <p class="text-gray-500">献立がありません</p>
                <% end %>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>