config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  get 'terms', to: 'tops#terms'
  get 'privacy', to: 'tops#privacy'

  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/guest_login', to: 'sessions#guest_login'

  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauths/oauth', to: 'oauths#oauth', as: :auth_at_provider

  resources :password_resets, only: %i[new create edit update]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :menus, only: %i[index edit update]

  resources :videos do
    get 'search_videos', on: :collection
  end

  resources :dishes, only: %i[index edit update]

  resource :profile, only: %i[show edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates :name, presence: true

  has_many :menus, dependent: :destroy
  has_one :video, dependent: :destroy
  has_many :dish_genre_tags, dependent: :destroy
  has_many :genre_tags, through: :dish_genre_tags
  has_many :dish_ingredient_tags, dependent: :destroy
  has_many :ingredient_tags, through: :dish_ingredient_tags

end

app/models/dish_genre_tag.rb
class DishGenreTag < ApplicationRecord
  belongs_to :dish
  belongs_to :genre_tag
end

app/models/dish_ingredient_tag.rb
class DishIngredientTag < ApplicationRecord
  belongs_to :dish
  belongs_to :ingredient_tag
end

app/models/genre_tag.rb
class GenreTag < ApplicationRecord
  has_many :dish_genre_tags, dependent: :destroy
  has_many :dishes, through: :dish_genre_tags

  validates :name, presence: true
end

app/models/ingredient_tag.rb
class IngredientTag < ApplicationRecord
  has_many :dish_ingredient_tags, dependent: :destroy
  has_many :dishes, through: :dish_ingredient_tags

  validates :name, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user
  belongs_to :dish

  def start_time
    self.date
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :menus, dependent: :destroy
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :name, presence: true, length: {maximum: 20}
  validates :email, presence: true, length: {maximum: 100}, uniqueness: true
  validates :password, length: { minimum: 7 }, confirmation: true, if: -> { new_record? || changes[:crypted_password] }

  validates :reset_password_token, uniqueness: true, allow_nil: true

  enum role: { general: 0, admin: 1 }
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :dish

  validates :video_id, presence: true, uniqueness: true
  validates :title, presence: true, uniqueness: true
  validates :thumbnail, presence: true, uniqueness: true

  def self.search_by_dish(dish)
    response = YoutubeService.list_searches(
      'snippet',
      q: dish.name + "レシピ",
      type: 'video',
      max_results: 1,
      # 関連度が高い順
      order: "relevance",
    ).items

    if response.present?
      video = Video.new(
        video_id: response.first.id.video_id,
        title: response.first.snippet.title,
        thumbnail: response.first.snippet.thumbnails.high.url,
        dish: dish
      )
      video.save
    end
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :require_login

  def index;  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '', admin = false)
    base_title = if admin
                  'MenuVid(管理画面)'
                 else
                  'MenuVid'
                 end
    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end

  def default_meta_tags
    {
      site: 'MenuVid',
      title: 'MenuVid',
      reverse: true,
      charset: 'utf-8',
      description: 'MenuVid(メニュービッド)は、Youtube動画であなただけの献立を自動で作成してくれるサービスです。',
      keywords: 'Youtube,献立,料理',
      canonical: request.original_url,
      separator: '|',
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.png'), # 配置するパスやファイル名によって変更すること
        local: 'ja-JP'
      },
      # Twitter用の設定を個別で設定する
      twitter: {
        card: 'summary_large_image', # Twitterで表示する場合は大きいカードにする
        site: '@', # アプリの公式Twitterアカウントがあれば、アカウント名を書く
        image: image_url('ogp.png') # 配置するパスやファイル名によって変更すること
      }
    }
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_google_analytics.html.erb
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DC2YV9QLBM"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DC2YV9QLBM');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="bumblebee">
  <head>
    <%= favicon_link_tag('favicon.png') %>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="MenuVid(メニュービッド)は、Youtube動画であなただけの献立を自動で作成してくれるサービスです">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/daisyui@2.51.6/dist/full.css" %>

    <%= javascript_importmap_tags %>

    <%= render 'layouts/google_analytics' %>

    <%= display_meta_tags(default_meta_tags) %>

  </head>

  <body>
    <% if logged_in? %>
      <%= render "shared/header" %>
    <% else %>
      <%= render "shared/before_header" %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_before_header.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <%= link_to (image_tag 'logo.png', alt: "MenuVid", size: "60x60"), menus_path(date: Date.today) %>
    <%= link_to 'MenuVid', root_path, class: "text-2xl normal-case font-bold" %>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <li>
        <%= link_to t('defaults.login'), login_path, class: "hover:text-orange-500 active:text-orange-700 text-lg font-semibold transition duration-100" %>
      </li>
      <li>
        <%= link_to t('defaults.register'), new_user_path, class: "hover:text-orange-500 active:text-orange-700 text-lg font-semibold transition duration-100" %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<div class="bg-white pt-4 sm:pt-10 lg:pt-12">
  <footer class="mx-auto max-w-screen-2xl px-4 md:px-8">
    <div class="flex flex-col items-center border-t pt-10">
      <nav class="mb-4 flex flex-wrap justify-center gap-x-4 gap-y-2 md:justify-start md:gap-6">
          <%= link_to t('defaults.terms_of_use'),  terms_path, class: "text-gray-800 font-bold tracking-widest" %>
          <%= link_to t('defaults.privacy_policy'),  privacy_path, class: "text-gray-800 font-bold tracking-widest"%>
          <%= link_to t('defaults.contact'), 'https://docs.google.com/forms/d/e/1FAIpQLSdN5oRG7bTu2z_U9vL6q22lwoHvxBPuGBpLkEjARkEJX2-zTQ/viewform?usp=sf_link', class: "text-gray-800 font-bold tracking-widest", target: "_blank" %>
      </nav>
    </div>
    <div class="py-8 text-center text-sm text-gray-400">
      © 2023 - MenuVid.
    </div>
  </footer>
</div>

app/views/shared/_header.html.erb
<header>
  <div class="navbar bg-base-100">
    <div class="navbar-start flex items-center">
      <%= link_to (image_tag 'logo.png', alt: "MenuVid", size: "60x60"), menus_path(date: Date.today) %>
      <%= link_to 'MenuVid', menus_path(date: Date.today), class: "text-2xl normal-case font-bold ml-2" %>
    </div>
    <div class="navbar-end flex items-center">
      <div class="dropdown dropdown-hover dropdown-end">
        <label tabindex="0" class="btn btn-ghost btn-circle">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
        </label>
        <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-200 rounded-box w-64">
          <li>
            <%= link_to t('defaults.menus'), menus_path(date: Date.today) %>
          </li>
          <li>
            <%= link_to t('defaults.mypage'), profile_path %>
          </li>
          <li>
            <%= button_to t('defaults.logout'), logout_path, method: :delete %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading ">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= start_date.year %>年<%= t('date.month_names')[start_date.month] %> </span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>