config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  get 'terms', to: 'tops#terms'
  get 'privacy', to: 'tops#privacy'

  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/guest_login', to: 'sessions#guest_login'

  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauths/oauth', to: 'oauths#oauth', as: :auth_at_provider

  resources :password_resets, only: %i[new create edit update]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :menus, only: %i[index edit update]

  resources :videos do
    get 'search_videos', on: :collection
  end

  resources :dishes, only: %i[index edit update]

  resource :profile, only: %i[show edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates :name, presence: true

  has_many :menus, dependent: :destroy
  has_one :video, dependent: :destroy
  has_many :dish_genre_tags, dependent: :destroy
  has_many :genre_tags, through: :dish_genre_tags
  has_many :dish_ingredient_tags, dependent: :destroy
  has_many :ingredient_tags, through: :dish_ingredient_tags

end

app/models/dish_genre_tag.rb
class DishGenreTag < ApplicationRecord
  belongs_to :dish
  belongs_to :genre_tag
end

app/models/dish_ingredient_tag.rb
class DishIngredientTag < ApplicationRecord
  belongs_to :dish
  belongs_to :ingredient_tag
end

app/models/genre_tag.rb
class GenreTag < ApplicationRecord
  has_many :dish_genre_tags, dependent: :destroy
  has_many :dishes, through: :dish_genre_tags

  validates :name, presence: true
end

app/models/ingredient_tag.rb
class IngredientTag < ApplicationRecord
  has_many :dish_ingredient_tags, dependent: :destroy
  has_many :dishes, through: :dish_ingredient_tags

  validates :name, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user
  belongs_to :dish

  def start_time
    self.date
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :menus, dependent: :destroy
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :name, presence: true, length: {maximum: 20}
  validates :email, presence: true, length: {maximum: 100}, uniqueness: true
  validates :password, length: { minimum: 7 }, confirmation: true, if: -> { new_record? || changes[:crypted_password] }

  validates :reset_password_token, uniqueness: true, allow_nil: true

  enum role: { general: 0, admin: 1 }
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :dish

  validates :video_id, presence: true, uniqueness: true
  validates :title, presence: true, uniqueness: true
  validates :thumbnail, presence: true, uniqueness: true

  def self.search_by_dish(dish)
    response = YoutubeService.list_searches(
      'snippet',
      q: dish.name + "レシピ",
      type: 'video',
      max_results: 1,
      # 関連度が高い順
      order: "relevance",
    ).items

    if response.present?
      video = Video.new(
        video_id: response.first.id.video_id,
        title: response.first.snippet.title,
        thumbnail: response.first.snippet.thumbnails.high.url,
        dish: dish
      )
      video.save
    end
  end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :require_login
  before_action :authenticate_admin

  def index
    @dishes = Dish.all
  end

  def edit
    @dish = Dish.find(params[:id])
    @genre_tags = GenreTag.all
    @ingredient_tags = IngredientTag.all
  end

  def update
    @dish = Dish.find(params[:id])
    if @dish.update(dish_params)
      redirect_to dishes_path
    else
      render :edit
    end
  end

  private

  def authenticate_admin
    redirect_to menus_path(date: Date.today), warning: "管理者権限を持っていません" unless current_user.admin?
  end

  def dish_params
    params.require(:dish).permit(:name, genre_tag_ids: [], ingredient_tag_ids: [])
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :require_login

  def index
    return unless params[:date].present?

    start_date = params[:date].to_date.beginning_of_week
    end_date = start_date.end_of_week
    @week_menus = current_user.menus.where(date: start_date..end_date).order(date: :asc)

    if @week_menus.empty?
      create_weekly_menu(start_date)
      flash[:notice] = "#{start_date} から #{end_date} までの献立を作成しました！"
      redirect_to action: :index, date: params[:date]
    end
  end

  def create_weekly_menu(start_date)
    (start_date..start_date.end_of_week).each do |date|
      create_menu_for_date(date)
    end
  end

  def create_menu_for_date(date)
    return if current_user.menus.exists?(date: date)
    previous_menu = current_user.menus.find_by(date: date - 1.day)
    previous_genre_id = previous_menu&.dish&.genre_tags&.pluck(:id)
    dish = Dish.joins(:genre_tags).where.not(genre_tags: { id: previous_genre_id }).order("RANDOM()").first
    current_user.menus.create(date: date, dish: dish)
  end

  def edit
    @menu = current_user.menus.find(params[:id])
    @dishes = Dish.all
  end

  def update
    @menu = current_user.menus.find(params[:id])
    @menu.update(dish_id: params[:menu][:dish_id])
    redirect_to menus_path(date: @menu.date)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :require_login

  def index;  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :require_login

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      redirect_to menus_path(date: Date.today), success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '', admin = false)
    base_title = if admin
                  'MenuVid(管理画面)'
                 else
                  'MenuVid'
                 end
    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end

  def default_meta_tags
    {
      site: 'MenuVid',
      title: 'MenuVid',
      reverse: true,
      charset: 'utf-8',
      description: 'MenuVid(メニュービッド)は、Youtube動画であなただけの献立を自動で作成してくれるサービスです。',
      keywords: 'Youtube,献立,料理',
      canonical: request.original_url,
      separator: '|',
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.png'), # 配置するパスやファイル名によって変更すること
        local: 'ja-JP'
      },
      # Twitter用の設定を個別で設定する
      twitter: {
        card: 'summary_large_image', # Twitterで表示する場合は大きいカードにする
        site: '@', # アプリの公式Twitterアカウントがあれば、アカウント名を書く
        image: image_url('ogp.png') # 配置するパスやファイル名によって変更すること
      }
    }
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/dishes/edit.html.erb
<h1 class="text-xl font-bold mb-4">Edit Dish</h1>

<%= form_with model: @dish, url: dish_path(@dish), method: :patch do |f| %>
  <div class="mb-4">
    <%= f.label :name, class: "block text-gray-700 font-bold mb-2" %>
    <%= f.text_field :name, class: "form-input mt-1 block w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
  </div>

  <div class="mb-4">
    <%= f.label :genre_tag_ids, class: "block text-gray-700 font-bold mb-2" %>
    <% @genre_tags.each do |genre_tag| %>
      <label class="inline-flex items-center">
        <%= check_box_tag "dish[genre_tag_ids][]", genre_tag.id, @dish.genre_tag_ids.include?(genre_tag.id), class: "form-checkbox h-5 w-5 text-indigo-600" %>
        <%= label_tag "dish_genre_tag_#{genre_tag.id}", genre_tag.name, class: "ml-2 text-gray-700 font-bold" %>
      </label>
    <% end %>
  </div>

  <div class="mb-4">
    <%= f.label :ingredient_tag_ids, class: "block text-gray-700 font-bold mb-2" %>
    <% @ingredient_tags.each do |ingredient_tag| %>
      <label class="inline-flex items-center">
        <%= check_box_tag "dish[ingredient_tag_ids][]", ingredient_tag.id, @dish.ingredient_tag_ids.include?(ingredient_tag.id), class: "form-checkbox h-5 w-5 text-indigo-600" %>
        <%= label_tag "dish_ingredient_tag_#{ingredient_tag.id}", ingredient_tag.name, class: "ml-2 text-gray-700 font-bold" %>
      </label>
    <% end %>
  </div>

  <%= f.submit "Update", class: "btn btn-prymary" %>
<% end %>

app/views/dishes/index.html.erb
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
  <% @dishes.each do |dish| %>
    <div class="bg-white rounded-lg shadow-lg">
      <%= link_to edit_dish_path(dish) do %>
        <div class="p-4">
          <div class="font-bold text-xl mb-2"><%= dish.name %></div>
          <div class="text-gray-700 text-base">
            <% if dish.genre_tags.present? %>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= dish.genre_tags.first.name %></span>
            <% end %>
            <% if dish.ingredient_tags.present? %>
              <% dish.ingredient_tags.each do |tag| %>
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= tag.name %></span>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/menus/edit.html.erb
<h1 class="text-3xl font-bold mb-6 text-center">献立変更</h1>

<div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl">

  <%= form_with model: @menu, local: true, class: "w-full " do |f| %>
    <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
      <div class="grid grid-cols-1 gap-6">
        <div>
          <%= f.label :dish_id, "献立を選択してください", class: "text-lg font-medium text-gray-700" %>
          <%= f.select :dish_id, options_for_select(@dishes.map {|d| [d.name, d.id]}, @menu.dish_id), {}, class: "select select-bordered w-full mt-1"%>
        </div>
      </div>
    </div>
    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
      <%= f.submit '変更する', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/menus/index.html.erb
<% content_for(:title, t('.title')) %>
<%# 献立一覧の親要素を追加 %>
<% if @week_menus.present? %>
  <div class="p-4">
    <div class="flex justify-center mb-4">
      <h1 class="text-4xl font-bold"><%= @week_menus.first.date.strftime('%-m/%-d')%>~<%= @week_menus.last.date.strftime('%-m/%-d') %>の献立</h1>
    </div>
    <div class="mb-4">
      <div class="mb-4 flex justify-center">
        <%= link_to '3週間前', menus_path(date: Date.today.prev_week.prev_week.prev_week), class: "btn btn-outline rounded-full flex-1" %>
        <%= link_to '先々週', menus_path(date: Date.today.prev_week.prev_week), class: "btn btn-outline rounded-full flex-1" %>
        <%= link_to '先週', menus_path(date: Date.today.prev_week), class: "btn btn-outline rounded-full flex-1" %>
        <%= link_to '今週', menus_path(date: Date.today), class: "btn btn-outline rounded-full flex-1" %>
        <%= link_to '来週', menus_path(date: Date.today.next_week), class: "btn btn-outline rounded-full flex-1" %>
      </div>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-4">
      <% @week_menus.each do |menu| %>
        <%# 献立のカードを追加 %>
        <div class="bg-white rounded-lg shadow-lg overflow-hidden mb-10">
          <%# 日付を表示 %>
          <div class="p-4 bg-gray-200">
            <h3 class="text-xl font-semibold text-center"><%= menu.date.strftime('%-m/%-d (%a)') %></h3>
          </div>
          <%# 動画を表示 %>
          <% if menu.dish.video.present? %>
            <div class="p-4 relative" style="padding-bottom: 56.25%;">
              <iframe class="absolute inset-0 w-full h-full object-cover object-center" src="https://www.youtube.com/embed/<%= menu.dish.video.video_id %>" frameborder="0" allow="fullscreen"></iframe>
            </div>
          <% else %>
            <h1>動画はありません</h1>
          <% end %>
          <%# 変更ボタンを表示 %>
          <div class="p-4 bg-white shadow-md rounded-lg">
            <div class="flex items-center justify-between">
              <div class="flex flex-col">
                <h3 class="text-lg font-semibold text-gray-800"><%= menu.dish.name %></h3>
                <% if menu.dish.present? && menu.dish.genre_tags.present? %>
                  <span class="text-sm font-medium text-gray-500 "><%= menu.dish.genre_tags.first.name %></span>
                <% end %>
                <% if menu.dish.ingredient_tags.first && menu.dish.ingredient_tags.first.name.present? %>
                  <div class="mt-1">
                    <% menu.dish.ingredient_tags.each do |tag| %>
                      <span class="inline-block px-2 py-1 text-sm font-semibold text-gray-700 bg-gray-200 rounded-full mr-2 mb-2"><%= tag.name %></span>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <%= link_to '変更する', edit_menu_path(menu.id), class: "btn btn-primary rounded-full"%>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="my-4">
      <div class="flex justify-center space-x-2">
        <%= link_to '3週間前', menus_path(date: Date.today.prev_week.prev_week.prev_week), class: "btn btn-outline rounded-full flex-1" %>
        <%= link_to '先々週', menus_path(date: Date.today.prev_week.prev_week), class: "btn btn-outline rounded-full flex-1" %>
        <%= link_to '先週', menus_path(date: Date.today.prev_week), class: "btn btn-outline rounded-full flex-1" %>
        <%= link_to '今週', menus_path(date: Date.today), class: "btn btn-outline rounded-full flex-1" %>
        <%= link_to '来週', menus_path(date: Date.today.next_week), class: "btn btn-outline rounded-full flex-1" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<!-- Form -->
  <%= form_with model: @user do |f| %>
    <% if user.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><i class="uil uil-exclamation-triangle mr-1"></i><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl">
      <div class="p-8">
          <div class="mb-6">
            <%= f.label :name, User.human_attribute_name(:name), class: "block mb-1 text-lg leading-tight font-medium text-gray-700" %>
            <%= f.text_field :name, class: "block w-full rounded-md bg-gray-200 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0 shadow-sm text-gray-700 py-3 px-4 placeholder-gray-400 placeholder-opacity-75", placeholder: "20文字以内でご入力ください" %>
          </div>
          <div class="mb-6">
            <%= f.label :email, User.human_attribute_name(:email), class: "block mb-1 text-lg leading-tight font-medium text-gray-700" %>
            <%= f.email_field :email, class: "block w-full rounded-md bg-gray-200 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0 shadow-sm text-gray-700 py-3 px-4 placeholder-gray-400 placeholder-opacity-75", placeholder: "メールアドレスをご入力ください" %>
          </div>
          <div class="mb-6">
            <%= f.label :password, User.human_attribute_name(:password), class: "block mb-1 text-lg leading-tight font-medium text-gray-700" %>
            <%= f.password_field :password, class: "block w-full rounded-md bg-gray-200 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0 shadow-sm text-gray-700 py-3 px-4 placeholder-gray-400 placeholder-opacity-75", placeholder: "7文字以上でご入力ください" %>
          </div>
          <div class="mb-6">
            <%= f.label :password_confirmation, class: "block mb-1 text-lg leading-tight font-medium text-gray-700" %>
            <%= f.password_field :password_confirmation, class: "block w-full rounded-md bg-gray-200 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0 shadow-sm text-gray-700 py-3 px-4 placeholder-gray-400 placeholder-opacity-75", placeholder: "確認用としてもう一度ご入力ください" %>
          </div>
          <div class="mt-10">
            <%= f.submit t('defaults.register'), class: 'btn btn-primary btn-block' %>
          </div>
      </div>
    </div>
  <% end %>

app/views/users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to 'New user', new_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="users" class="min-w-full">
    <%= render @users %>
  </div>
</div>

app/views/users/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl text-center text-gray-800 mb-10">
    <span class="block font-black text-5xl text-primary-500 mb-2">
      <%= t('.title') %>
    </span>
    <span class="bg-primary-500 h-1 w-20 block mx-auto"></span>
  </h1>
  <%= render "form", user: @user %>
</div>